version: 0.0
os: linux
files:
  - source: /app
    destination: /home/ec2-user/acebook/
permissions:
  - object: /home/ec2-user/acebook/
    pattern: "**"
    owner: ec2-user
    group: wheel
    mode: 777
hooks:
  BeforeInstall:
    - location: before_install.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: application_start.sh
      timeout: 300
      runas: ec2-user
