---
version: 0.0
os: linux
files:
  - source: /app.js
    destination: /home/ec2-user/acebook/app.js
  - source: /bin
    destination: /home/ec2-user/acebook/bin
  - source: /controllers
    destination: /home/ec2-user/acebook/controllers
  - source: /models
    destination: /home/ec2-user/acebook/models
  - source: /package-lock.json
    destination: /home/ec2-user/acebook/package-lock.json
  - source: /package.json
    destination: /home/ec2-user/acebook/package.json
  - source: /public
    destination: /home/ec2-user/acebook/public
  - source: /routes
    destination: /home/ec2-user/acebook/routes
  - source: /spec
    destination: /home/ec2-user/acebook/spec
  - source: /views
    destination: /home/ec2-user/acebook/views
permissions:
  - object: /home/ec2-user/acebook/
    pattern: "**"
    owner: ec2-user
    group: wheel
    mode: 777
hooks:
  BeforeInstall:
    - location: before_install.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: application_start.sh
      timeout: 300
      runas: ec2-user
